#+TITLE:     Scott Ambler, cliffhangers
#+EMAIL:     thomas@kjeldahlnilsson.net
#+DATE:      03.06.2006
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS: H:3 num:nil toc:nil @:t ::t |:t ^:t -:t f:t *:t <:t 
#+OPTIONS: TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:
#+LINK_HOME:
#+XSLT:

#+BEGIN_HTML
<p class="storycontent">Attended a seminar held by Scott Ambler at <a href="http://bouvet.no/">Bouvet</a> this tuesday. I saw him at <a href="http://www.javapolis.com/">Javapolis</a> last fall, so a fair bit of the material was pure repetition - but he's still a very inspiring guy. Agile methods, modelling and database techniques galore, not to mention a fair bit of ranting about traditional software development in general and dba people in particular.</p>

<p>The basic message was this: <strong>Developers should learn more about database stuff, db people should learn more about object oriented development, and <em>everyone</em> should learn more about agile methodology.</strong></p>

<p>Good stuff, highly recommended. Check his <a href="http://www.ambysoft.com/">site</a>, there's a ton of material there!</p>

<p>This is what I'd like to see, though: a similar Ambler seminar, but geared towards an audience of both developers and db guys, the theme being something along the lines of "poking holes in the cultural walls between developers and database administrators" Only with a better title. I did suggest this to the organizers. Fingers crossed!</p>

<p>And finally, I picked up a neat new expression this week (probably from some blog at the <a href="http://butunclebob.com/"> Uncle Bob</a> site. Not able to retrieve the post in question now though).</p>

<p><strong><em>"Ending the day on a cliffhanger"</em></strong> : The act of reaching some seemingly insurmountable coding problem at the end of a work day... only to leave it, come back fresh the next morning and have it dissolve like morning mist.</p>

<p>Gotta love it when that happens... and now I have a snappy expression for it!</p>
#+END_HTML
